
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-06
owner: ucsb-cs156-s26
repo_name: team02-s26-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MDk3OTY3","is_bot":false,"login":"roy-lee7473","name":"Roy Lee"},"headRefName":"rl-ucsborganization-index","number":99,"title":"Rl ucsborganization index","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/99"},{"author":{"id":"U_kgDOCVG5mA","is_bot":false,"login":"dongyi-xia","name":""},"headRefName":"dx-recommendation-request-placeholder-pages","number":96,"title":"dx - add placeholder pages for Index, Edit, Create for Recommendation…","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/96"},{"author":{"id":"U_kgDOCeSMMQ","is_bot":false,"login":"Mr465truck","name":""},"headRefName":"ev-menuitems-implement-index-page","number":93,"title":"Ev menuitems implement index page","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/93"},{"author":{"id":"U_kgDOCeSMMQ","is_bot":false,"login":"Mr465truck","name":""},"headRefName":"ev-menuitems-implement-edit-page","number":92,"title":"Ev menuitems implement edit page","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/92"},{"author":{"id":"U_kgDOCeSMMQ","is_bot":false,"login":"Mr465truck","name":""},"headRefName":"ev-menuitems-implement-create-page","number":91,"title":"Ev menuitems implement create page","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/91"},{"author":{"id":"U_kgDOCvx1hg","is_bot":false,"login":"aidenhunter66","name":"Aiden"},"headRefName":"ah-edit-page-mir","number":78,"title":"Ah edit page mir","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/78"},{"author":{"id":"U_kgDOCvx1hg","is_bot":false,"login":"aidenhunter66","name":"Aiden"},"headRefName":"ah-index-page=mir","number":77,"title":"ah-index-page-mir","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/77"},{"author":{"id":"U_kgDOCvx1hg","is_bot":false,"login":"aidenhunter66","name":"Aiden"},"headRefName":"create-page-menuitemreview","number":76,"title":"Create page menuitemreview","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/76"},{"author":{"id":"U_kgDOCvx1hg","is_bot":false,"login":"aidenhunter66","name":"Aiden"},"headRefName":"ah-copy-placeholders-pages","number":75,"title":"Ah copy placeholders pages","url":"https://github.com/ucsb-cs156-s26/team02-s26-06/pull/75"}]
